- name: ANTM
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: TLKM
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: KLBF
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: BBCA
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: ARTO
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: ISAT
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: EXCL
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: AALI
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: TKIM
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20
- name: GGRM
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 150
  distance: 20
- name: UNVR
  hf_repo: /home/yogi/chronos-research/dataset/daily-all
  offset: -50
  prediction_length: 50
  num_rolls: 1
  max_history: 75
  distance: 20