name: CI

on:
  push:
    branches: ["**"] # Run on any branch
  pull_request:
    branches: ["**"] # Run on any branch
  schedule:
    - cron: "0 8 * * *" # Run at 8 AM UTC

jobs:
  type-check:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install ".[typecheck]" -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: Type checks with mypy
        run: mypy src test

  test:
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install ".[test]" -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: Test with pytest
        run: pytest
