training_data_paths:
- "/home/yogi/chronos-research/arrow_data/42-LQ45.arrow"
- "/home/yogi/chronos-research/chronos-forecasting/scripts/kernelsynth-data.arrow"
probability:
- 0.8
- 0.2
context_length: 512
prediction_length: 64
min_past: 60
max_steps: 400_000
save_steps: 100_000
log_steps: 500
per_device_train_batch_size: 32
learning_rate: 0.0001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 200_000
gradient_accumulation_steps: 2
model_id: amazon/chronos-t5-small
model_type: seq2seq
random_init: false
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.15
dataloader_num_workers: 1
max_missing_prop: 0
use_eos_token: true
