- name: ETTh
  hf_repo: autogluon/chronos_datasets_extra
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 75
  distance: 20
- name: ETTh
  hf_repo: autogluon/chronos_datasets_extra
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 75
  distance: 20
- name: ETTh
  hf_repo: autogluon/chronos_datasets_extra
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 100
  distance: 20
- name: ETTh
  hf_repo: autogluon/chronos_datasets_extra
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 150
  distance: 20