- name: nn5
  hf_repo: autogluon/chronos_datasets
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 50
  distance: 20
- name: nn5
  hf_repo: autogluon/chronos_datasets
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 75
  distance: 20
- name: nn5
  hf_repo: autogluon/chronos_datasets
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 100
  distance: 20
- name: nn5
  hf_repo: autogluon/chronos_datasets
  offset: -20
  prediction_length: 20
  num_rolls: 1
  max_history: 150
  distance: 20
