- name: monash_m1_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -5
  prediction_length: 5
  num_rolls: 1
  max_history: 10
  distance: 20
- name: monash_m1_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -5
  prediction_length: 5
  num_rolls: 1
  max_history: 15
  distance: 20
- name: monash_m1_monthly 
  hf_repo: autogluon/chronos_datasets
  offset: -5
  prediction_length: 5
  num_rolls: 1
  max_history: 18
  distance: 20
- name: monash_m1_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -5
  prediction_length: 5
  num_rolls: 1
  max_history: 21
  distance: 20